ingress:
  enabled: true
  className: alb
  annotations: {}
    alb.ingress.kubernetes.io/target-type: ip
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: myapp.salesdemo-apps.duplocloud.net
      paths:
        - path: /
          pathType: ImplementationSpecific
