apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/managed-by: Kustomize
  app.kubernetes.io/part-of: myapp
  app.kubernetes.io/component: database
resources:
- statefulset.yaml
- service.yaml
secretGenerator:
- name: postgresql
  literals:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_DB=postgres
generatorOptions:
  disableNameSuffixHash: true
