apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  selector: {}
  serviceName: postgresql
  replicas: 1 
  template:
    spec:
      nodeSelector: {}
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgresql
        image: postgresql
        envFrom:
        - secretRef:
            name: postgresql
        ports:
        - name: psql
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          # updated by patching
          storage: 1Gi
