apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name myapp-green
  namespace: &namespace duploservices-demo02
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: demo02-green
    app.kubernetes.io/version: &version HEAD
    app.kubernetes.io/part-of: &project myapp
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: apps
spec:
  project: *project
  destination:
    namespace: *namespace
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/duplocloud/argocd-example.git
    path: apps/myapp
    targetRevision: *version
    helm:
      releaseName: *name
      valueFiles:
      - ../../env/demo/values.yaml
      valuesObject:
        ingress:
          enabled: false

